name: Deploy Github Pages 

on:
    push:
     branches: 
        - main
    # workflow_dispatch:
    #     branches:
    #         - main

permissions: 
    contents: read 
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    build:
        environment: production
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./vite-project
        steps:
            - name: Fetch Code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm install
            - name: Build 
              run: npm run build
            - name: Generate Artifact
              uses: actions/upload-artifact@v3
              with:
                name: artifact
                path: ./vite-project/dist

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment: 
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Configure Github Pages
              uses: action/configure-pages@v4
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v3
              with:
               artifact_name: artifact

